services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=root
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
    command: >
      sh -c "alembic upgrade head &&
             uvicorn appfastapi.main:app --host 0.0.0.0 --port 8000 --reload"

  celery_worker:
    build: .
    depends_on:
      - redis
      - web
    command: celery -A appfastapi.mycelery worker -P solo -l info
    volumes:
      - .:/app

  celery_weather:
    build: .
    depends_on:
      - redis
      - web
    command: celery -A appfastapi.weathercelery worker -P solo -l info
    volumes:
      - .:/app

  celery_beat:
    build: .
    depends_on:
      - redis
      - web
    command: celery -A appfastapi.weathercelery beat -l info
    volumes:
      - .:/app

  postgres:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
